---

- name: ensure wget is installed
  yum:
    name: wget
    state: present


- name: Download Java
  command: 'wget -q -O "{{ java_archive }}" --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" "{{ java_download_url }}"'

- name: install java
  yum:
    name: "{{ java_archive }}"
    state: present

- name: Clean up
  file:
    state: absent
    path: "{{ java_archive }}"
