---

- name: installing repo for Java 8 in Ubuntu
  apt_repository: repo='ppa:openjdk-r/ppa'

- name: Ensure Java is installed.
  apt: 
    name: "{{ item }}"
    state: present
  with_items: "{{ java_packages }}"
