---
- name: Add repository for java 8
  apt_repository:
    repo: 'ppa:webupd8team/java'
    update_cache: yes

- name: Accepr Java 8 License
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Ensure Java is installed.
  apt:
    pkg: "{{ item }}"
    state: present
  with_items: "{{ java_packages }}"

